### ISSUE TITLE
Occasionally commit.summary is undefined

### ISSUE THREAD

**Issue by iwhitfield** [rvagg/changelog-maker#14]
I haven't had much time to debug this properly, so I dunno if the root is something in the repo I'm using (hope not, it's private so I can't share access), or the lib this util is using, but it can be protected against. 

Here is my usage (on io.js):

```
IWhitfieldMBPR:master iwhitfield$ changelog-maker --start-ref=f3f513790f71eaffe23d18efb790b234ef88328c <redacted-org> <redacted-repo>
/Users/iwhitfield/.nvm/versions/io.js/v2.3.1/lib/node_modules/changelog-maker/changelog-maker.js:97
  var summary = commit.summary.replace(revertRe, '')
                              ^
TypeError: Cannot read property 'replace' of undefined
    at commitToGroup (/Users/iwhitfield/.nvm/versions/io.js/v2.3.1/lib/node_modules/changelog-maker/changelog-maker.js:97:31)
    at commitToOutput (/Users/iwhitfield/.nvm/versions/io.js/v2.3.1/lib/node_modules/changelog-maker/changelog-maker.js:162:18)
    at Array.map (native)
    at Immediate._onImmediate (/Users/iwhitfield/.nvm/versions/io.js/v2.3.1/lib/node_modules/changelog-maker/changelog-maker.js:210:17)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```

So I dug a little, and put in some logging and it somehow appears that this commit is being passed in:

```
{ sha: 'eb27d2e12431656b6725ff665c9c2babbc59ab39',
  author: 
   { name: 'Isaac Whitfield',
     email: 'iwhitfield@appcelerator.com' },
  prUrl: 'eoptimize distinct queries' }
```

But of course... no summary property. It appears something has gone wrong with the parsing somewhere - the summary was initially `Preoptimize distinct queries`, which explains the `pr` in the field name, and why the value makes no sense.

Regardless of whether this is a lib issue or not, I think it's pretty safe to add some protection to `changelog-maker`. In my case, I edited the blocks in question to:

```
function commitToGroup (commit) {
  if (commit.summary !== undefined) {
    var summary = commit.summary.replace(revertRe, '')
      , m       = summary.match(groupRe)
  }
  return m && m[1]
}
```

and

```
data.summary = commit.summary && commit.summary.replace(revertRe, '').replace(/"$/, '').replace(groupRe, '') || ''
```

I just want to make sure that there are no adverse effects of this and whether this is deemed something which should be protected against in the first place. 

As I said, haven't narrowed down the root cause but I'll keep looking when I get a chance.

**Comment by maboiteaspam** [comment]
I ll close it for now, if you detect it again, feel free to re open. 

Thanks for your report.
