### ISSUE TITLE
Markdown issues in 1.4.0 release

### ISSUE THREAD

**Issue by jamsyoung** [rvagg/changelog-maker#19]
I noticed this difference in the upgrade from 1.3.10 to 1.4.0

1.4.0 outputs this:

```markdown
* [[e09e75b338](https://github.com/organization/private-repo/commit/e09e75b338) - subsystem: summary (James Young) #220
```
* [[e09e75b338](https://github.com/organization/private-repo/commit/e09e75b338) - subsystem: summary (James Young) #220

1.3.10 would output this:

```markdown
* [[`361ac84d97`](https://github.com/organization/private-repo/commit/361ac84d97)] - **subsystem**: summary (James Young) [#214](https://github.com/organization/private-repo/pull/214)
```
* [[`361ac84d97`](https://github.com/organization/private-repo/commit/361ac84d97)] - **subsystem**: summary (James Young) [#214](https://github.com/organization/private-repo/pull/214)

I haven't had a chance to look at the changes yet, but wanted to go ahead and log the issue.

**Comment by rvagg** [comment]
ouch! @maboiteaspam this is some missing code when you converted away from template strings I guess

**Comment by maboiteaspam** [comment]
amh. So sorry about that. indeed, i squashed the md version at some moment (...).

I ll check this and push a fix later today.
https://github.com/maboiteaspam/changelog-maker/commit/80d8c10132dd6fd7089177276593b03386643efd
