### ISSUE TITLE
` instead of ' break the execution

### ISSUE THREAD

**Issue by Kikobeats** [rvagg/changelog-maker#2]
I suppose that you are using a real UNIX SO instead of Mac :P

```js
changelog-maker joyent/node

/usr/local/lib/node_modules/changelog-maker/changelog-maker.js:25
          configName : `changelog-maker`
                       ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by rvagg** [comment]
Sorry, using ES6 template strings as available in io.js, that particular line doesn't actually need them (I'll fix that) but other lines do.

I might accept a pull request to change to standard strings if you somehow manage to do it without making it bloated and ugly but I don't personally have a use for this _not_ running on io.js, sorry.

**Comment by Kikobeats** [comment]
what do you think about use [es6-template](https://github.com/esnext/es6-templates) polyfill for the node compatibility?

**Comment by rvagg** [comment]
it's a transpiler rather than a polyfill and I'm not a huge fan of transpilation steps in my modules cause I hate debugging that mess

**Comment by Kikobeats** [comment]
Understood. Thanks! :-)
